# Generated by Django 4.0.4 on 2022-06-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hash',
            new_name='hash_data',
        ),
    ]
