# Generated by Django 4.0.4 on 2022-06-12 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_hash_hash_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='time',
        ),
        migrations.RemoveField(
            model_name='hash_data',
            name='time',
        ),
    ]
