# Generated by Django 4.0.4 on 2022-06-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_comments_time_remove_hash_data_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='parent',
            field=models.IntegerField(default=0),
        ),
    ]
