# Generated by Django 4.0.4 on 2022-06-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_comments_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='notifications',
            field=models.CharField(default='', max_length=200),
        ),
    ]
