# Generated by Django 4.0.4 on 2022-06-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_users_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='notifications',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
